version: '2'
services:
  nginx:
    build: .
    env_file: .env
    environment:
      SERVICE_NAME: router
    ports:
      - 80:80
    links:
      - consul
    depends_on:
      - registrator
    restart: on-failure:10
  consul:
    image: consul
    env_file: .env
    command: agent -server -ui -client 0.0.0.0 -bootstrap-expect=1
    restart: on-failure:10
  registrator:
    image: gliderlabs/registrator:latest
    env_file: .env
    links:
      - consul
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: consul://consul:8500 
    depends_on:
      - consul
    restart: on-failure:10
