scrape_configs:
  - job_name: node
    scrape_interval: 5s
    static_configs:
    - targets: ['ip_node_explorer:9100']
rule_files:
    - './con.yml'
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['ip_alertmanager:9093']
