version: '3.2'
services:
  prometheus:
    image: prom/prometheus
    volumes:
        - ./prometheus:/etc/prometheus/
    command:
        - --config.file=/etc/prometheus/prometheus.yml
    ports:
        - 9090:9090
    restart: always
   
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    restart: always

volumes:
  grafana-storage:
