version: '3.2'
services:
  prometheus:
    image: prom/prometheus
    volumes:
        - ./prometheus:/etc/prometheus/
    command:
        - --config.file=/etc/prometheus/prometheus.yml
    ports:
        - 9090:9090
    restart: always
   
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    restart: always
    
  consul:
    command: -server -bootstrap -advertise 127.0.0.1
    image: progrium/consul
    container_name: consul
    labels:
      SERVICE_IGNORE: 'yes'
    ports:
      - "8500:8500"
      
  nginx:
    build: ./nginx
    container_name: nginx
    links:
      - consul
    ports:
      - "80:80"
    labels:
      SERVICE_IGNORE: 'yes'
    
volumes:
  grafana-storage:
