FROM werrio5/jre11

ADD https://github.com/werrio5/RSOI-labs/tree/master/apps/microprofile-health-quickstart-1.0-SNAPSHOT-runner.jar /deployments/app.jar
ENTRYPOINT ["java", "-jar", "deployments/app.jar"]
