FROM archlinux/base

RUN pacman -Sy
RUN pacman -S jre11-openjdk --noconfirm

ENV SERVER_IP 192.168.1.7

COPY dockerApp/target/*.jar /deployments/app.jar
ENTRYPOINT ["java", "-jar", "deployments/app.jar"]
