groups:
- name: ExporterDown
  rules:
  - alert: NodeDown
    expr: up{job='Node'} == 0
    for: 1m
    labels:
      severity: Error
    annotations:
      summary: "Node Explorer instance ($instance) down"
      description: "NodeExporterDown"
      
- name: AppAlerts
  rules:
  - alert: NotPrimeNumber
    expr: application_org_acme_microprofile_metrics_PrimeNumberChecker_notPrimeNumbersCount > 0
    for: 1s
    labels:
      severity: Error
    annotations:
      summary: "not prime number received"
      description: "YEPP BOAT"
      
- name: RuleThree
  rules:
  - alert: Received3ThreeTimes
    expr: application_org_acme_microprofile_metrics_PrimeNumberChecker_number3Count == 3
    for: 1s
    labels:
      severity: Error
    annotations:
      summary: "number 3 received 3 times"
      description: "UNACCEPTABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBLE"
