  
global:
  scrape_interval: 35s
  evaluation_interval: 35s
  scrape_timeout: 35s  

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'consul'
    consul_sd_configs:
      - server: '192.168.1.15:8500'
